vich_uploader:
    db_driver: orm

    mappings:
        restaurant_image:
            uri_prefix: /images/restaurants
            upload_destination: "%kernel.project_dir%/public/images/restaurants"
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        plat_image:
            uri_prefix: /images/plats
            upload_destination: "%kernel.project_dir%/public/images/plats"
            namer: Vich\UploaderBundle\Naming\UniqidNamer
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
