<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNdSVlxR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNdSVlxR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNdSVlxR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNdSVlxR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNdSVlxR\App_KernelDevDebugContainer([
    'container.build_hash' => 'NdSVlxR',
    'container.build_id' => '90786f3a',
    'container.build_time' => 1591170373,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNdSVlxR');
