<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4sOovWk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4sOovWk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4sOovWk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4sOovWk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4sOovWk\App_KernelDevDebugContainer([
    'container.build_hash' => '4sOovWk',
    'container.build_id' => '726dbbc3',
    'container.build_time' => 1590409835,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4sOovWk');
