<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVkq6LxA\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVkq6LxA/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVkq6LxA.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVkq6LxA\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVkq6LxA\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Vkq6LxA',
    'container.build_id' => '3c7bb4eb',
    'container.build_time' => 1589147922,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVkq6LxA');
