<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_twig_error_test' => [['code', '_format'], ['_controller' => 'twig.controller.preview_error::previewErrorPageAction', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception::showAction'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception::cssAction'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'admin_login_action' => [[], ['_controller' => 'App\\Controller\\AdminController::Login'], [], [['text', '/Login']], [], []],
    'admin_homepage_action' => [[], ['_controller' => 'App\\Controller\\AdminController::Admin_Index'], [], [['text', '/Admin_Dashboard']], [], []],
    'admin_logout' => [[], ['_controller' => 'App\\Controller\\AdminController::Admin_Logout'], [], [['text', '/Admin_Logout']], [], []],
    'homepage' => [[], ['_controller' => 'App\\Controller\\FrontController::index'], [], [['text', '/']], [], []],
    'front_menu' => [[], ['_controller' => 'App\\Controller\\FrontController::FrontMenu'], [], [['text', '/FrontMenu']], [], []],
    'user_login_action' => [[], ['_controller' => 'App\\Controller\\FrontController::UserLogin'], [], [['text', '/user/login']], [], []],
    'users_register' => [[], ['_controller' => 'App\\Controller\\FrontController::UsersRegister'], [], [['text', '/Register']], [], []],
    'users_logout' => [[], ['_controller' => 'App\\Controller\\FrontController::Users_Logout'], [], [['text', '/Users_Logout']], [], []],
    'front_restaurants_list' => [[], ['_controller' => 'App\\Controller\\FrontController::Front_Restaurants_LISt'], [], [['text', '/Restaurants']], [], []],
    'admin_restaurant' => [[], ['_controller' => 'App\\Controller\\RestaurantController::Restaurant'], [], [['text', '/Admin_Restaurant']], [], []],
    'admin_restaurant_insert' => [[], ['_controller' => 'App\\Controller\\RestaurantController::Restaurant_Insert'], [], [['text', '/Admin_Restaurant_Insert']], [], []],
    'admin_restaurant_update' => [['id'], ['_controller' => 'App\\Controller\\RestaurantController::Restaurant_Update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/Admin_Restaurant_Update']], [], []],
    'admin_restaurant_delete' => [['id'], ['_controller' => 'App\\Controller\\RestaurantController::Restaurant_Delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/Restaurant_Delete']], [], []],
];
